### ISSUE TITLE
Methods to bail out if conditions are met would be useful

### ISSUE THREAD

**Issue by robrwo** [kablamo/Test-WWW-Selenium-More#12]
Something like $sel->bailout_if( $foo )

**Comment by kablamo** [comment]
Hi!  Thanks for the suggestion.  Not sure that I understand.  How about an example of when that would be useful.

**Comment by robrwo** [comment]
Actually, thinking about this, it doesn't need to be in a method. The syntax of adding conditions to chained methods is messy.
